[package]
name = "sayori_get"
version = "1.0.2"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["stream"] }
serde_json = "1.0"
futures-util = "0.3.14"
tokio = { version = "1.21.2", features = ["full"] }
ndraey_downloader = "0.1.1"
