name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Packages
      run: sudo apt list gcc*mingw* && apt install gcc-mingw-w64 rustup
    - name: Install New Rustup Target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --release --target x86_64-pc-windows-gnu
    
