name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Packages
      run: sudo apt install gcc-mingw-w64-x86-64-win32*
    - name: Build
      run: cargo build --release --target x86_64-pc-windows-gnu
    
