name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Packages
      run: sudo apt list gcc*mingw* && sudo apt install gcc-mingw-w64 -y
    - name: Check rustup
      run: echo `which rustup`
    - name: Install New Rustup Target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --release --target x86_64-pc-windows-gnu
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: Hi
        draft: false
        prerelease: false
